
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BigMonitor(object):
    def setupUi(self, BigMonitor):
        BigMonitor.setObjectName("BigMonitor")
        BigMonitor.resize(1080, 910)
        self.centralwidget = QtWidgets.QWidget(BigMonitor)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setStyleSheet("")
        self.left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_frame.setLineWidth(0)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_head_frame = QtWidgets.QFrame(self.left_frame)
        self.left_head_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.left_head_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.left_head_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_head_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_head_frame.setLineWidth(0)
        self.left_head_frame.setObjectName("left_head_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_head_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.left_head_frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.left_head_frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.left_head_frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(0)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addWidget(self.left_head_frame)
        self.left_body_frame = QtWidgets.QFrame(self.left_frame)
        self.left_body_frame.setStyleSheet("color: rgb(255, 217, 61);")
        self.left_body_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_body_frame.setLineWidth(0)
        self.left_body_frame.setObjectName("left_body_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_body_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.car1l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car1l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car1l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car1l_frame.setLineWidth(0)
        self.car1l_frame.setObjectName("car1l_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.car1l_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.num_plate1_left_label = QtWidgets.QLabel(self.car1l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate1_left_label.setFont(font)
        self.num_plate1_left_label.setStyleSheet("")
        self.num_plate1_left_label.setText("")
        self.num_plate1_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate1_left_label.setObjectName("num_plate1_left_label")
        self.horizontalLayout_4.addWidget(self.num_plate1_left_label)
        self.zone1_left_label = QtWidgets.QLabel(self.car1l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone1_left_label.setFont(font)
        self.zone1_left_label.setStyleSheet("")
        self.zone1_left_label.setText("")
        self.zone1_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone1_left_label.setObjectName("zone1_left_label")
        self.horizontalLayout_4.addWidget(self.zone1_left_label)
        self.bay1_left_label = QtWidgets.QLabel(self.car1l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay1_left_label.setFont(font)
        self.bay1_left_label.setStyleSheet("")
        self.bay1_left_label.setText("")
        self.bay1_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay1_left_label.setObjectName("bay1_left_label")
        self.horizontalLayout_4.addWidget(self.bay1_left_label)
        self.verticalLayout_3.addWidget(self.car1l_frame)
        self.car2l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car2l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car2l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car2l_frame.setObjectName("car2l_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.car2l_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.num_plate2_left_label = QtWidgets.QLabel(self.car2l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate2_left_label.setFont(font)
        self.num_plate2_left_label.setStyleSheet("")
        self.num_plate2_left_label.setText("")
        self.num_plate2_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate2_left_label.setObjectName("num_plate2_left_label")
        self.horizontalLayout_5.addWidget(self.num_plate2_left_label)
        self.zone2_left_label = QtWidgets.QLabel(self.car2l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone2_left_label.setFont(font)
        self.zone2_left_label.setStyleSheet("")
        self.zone2_left_label.setText("")
        self.zone2_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone2_left_label.setObjectName("zone2_left_label")
        self.horizontalLayout_5.addWidget(self.zone2_left_label)
        self.bay2_left_label = QtWidgets.QLabel(self.car2l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay2_left_label.setFont(font)
        self.bay2_left_label.setStyleSheet("")
        self.bay2_left_label.setText("")
        self.bay2_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay2_left_label.setObjectName("bay2_left_label")
        self.horizontalLayout_5.addWidget(self.bay2_left_label)
        self.verticalLayout_3.addWidget(self.car2l_frame)
        self.car3l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car3l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car3l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car3l_frame.setObjectName("car3l_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.car3l_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.num_plate3_left_label = QtWidgets.QLabel(self.car3l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate3_left_label.setFont(font)
        self.num_plate3_left_label.setStyleSheet("")
        self.num_plate3_left_label.setText("")
        self.num_plate3_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate3_left_label.setObjectName("num_plate3_left_label")
        self.horizontalLayout_6.addWidget(self.num_plate3_left_label)
        self.zone3_left_label = QtWidgets.QLabel(self.car3l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone3_left_label.setFont(font)
        self.zone3_left_label.setStyleSheet("")
        self.zone3_left_label.setText("")
        self.zone3_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone3_left_label.setObjectName("zone3_left_label")
        self.horizontalLayout_6.addWidget(self.zone3_left_label)
        self.bay3_left_label = QtWidgets.QLabel(self.car3l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay3_left_label.setFont(font)
        self.bay3_left_label.setStyleSheet("")
        self.bay3_left_label.setText("")
        self.bay3_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay3_left_label.setObjectName("bay3_left_label")
        self.horizontalLayout_6.addWidget(self.bay3_left_label)
        self.verticalLayout_3.addWidget(self.car3l_frame)
        self.car4l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car4l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car4l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car4l_frame.setObjectName("car4l_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.car4l_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.num_plate4_left_label = QtWidgets.QLabel(self.car4l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate4_left_label.setFont(font)
        self.num_plate4_left_label.setStyleSheet("")
        self.num_plate4_left_label.setText("")
        self.num_plate4_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate4_left_label.setObjectName("num_plate4_left_label")
        self.horizontalLayout_7.addWidget(self.num_plate4_left_label)
        self.zone4_left_label = QtWidgets.QLabel(self.car4l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone4_left_label.setFont(font)
        self.zone4_left_label.setStyleSheet("")
        self.zone4_left_label.setText("")
        self.zone4_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone4_left_label.setObjectName("zone4_left_label")
        self.horizontalLayout_7.addWidget(self.zone4_left_label)
        self.bay4_left_label = QtWidgets.QLabel(self.car4l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay4_left_label.setFont(font)
        self.bay4_left_label.setStyleSheet("")
        self.bay4_left_label.setText("")
        self.bay4_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay4_left_label.setObjectName("bay4_left_label")
        self.horizontalLayout_7.addWidget(self.bay4_left_label)
        self.verticalLayout_3.addWidget(self.car4l_frame)
        self.car5l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car5l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car5l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car5l_frame.setObjectName("car5l_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.car5l_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.num_plate5_left_label = QtWidgets.QLabel(self.car5l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate5_left_label.setFont(font)
        self.num_plate5_left_label.setStyleSheet("")
        self.num_plate5_left_label.setText("")
        self.num_plate5_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate5_left_label.setObjectName("num_plate5_left_label")
        self.horizontalLayout_8.addWidget(self.num_plate5_left_label)
        self.zone5_left_label = QtWidgets.QLabel(self.car5l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone5_left_label.setFont(font)
        self.zone5_left_label.setStyleSheet("")
        self.zone5_left_label.setText("")
        self.zone5_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone5_left_label.setObjectName("zone5_left_label")
        self.horizontalLayout_8.addWidget(self.zone5_left_label)
        self.bay5_left_label = QtWidgets.QLabel(self.car5l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay5_left_label.setFont(font)
        self.bay5_left_label.setStyleSheet("")
        self.bay5_left_label.setText("")
        self.bay5_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay5_left_label.setObjectName("bay5_left_label")
        self.horizontalLayout_8.addWidget(self.bay5_left_label)
        self.verticalLayout_3.addWidget(self.car5l_frame)
        self.car6l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car6l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car6l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car6l_frame.setObjectName("car6l_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.car6l_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.num_plate6_left_label = QtWidgets.QLabel(self.car6l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate6_left_label.setFont(font)
        self.num_plate6_left_label.setStyleSheet("")
        self.num_plate6_left_label.setText("")
        self.num_plate6_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate6_left_label.setObjectName("num_plate6_left_label")
        self.horizontalLayout_9.addWidget(self.num_plate6_left_label)
        self.zone6_label = QtWidgets.QLabel(self.car6l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone6_label.setFont(font)
        self.zone6_label.setStyleSheet("")
        self.zone6_label.setText("")
        self.zone6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone6_label.setObjectName("zone6_label")
        self.horizontalLayout_9.addWidget(self.zone6_label)
        self.bay6_left_label = QtWidgets.QLabel(self.car6l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay6_left_label.setFont(font)
        self.bay6_left_label.setStyleSheet("")
        self.bay6_left_label.setText("")
        self.bay6_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay6_left_label.setObjectName("bay6_left_label")
        self.horizontalLayout_9.addWidget(self.bay6_left_label)
        self.verticalLayout_3.addWidget(self.car6l_frame)
        self.car7l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car7l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car7l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car7l_frame.setObjectName("car7l_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.car7l_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.num_plate7_left_label = QtWidgets.QLabel(self.car7l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate7_left_label.setFont(font)
        self.num_plate7_left_label.setStyleSheet("")
        self.num_plate7_left_label.setText("")
        self.num_plate7_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate7_left_label.setObjectName("num_plate7_left_label")
        self.horizontalLayout_10.addWidget(self.num_plate7_left_label)
        self.zone_left_label = QtWidgets.QLabel(self.car7l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone_left_label.setFont(font)
        self.zone_left_label.setStyleSheet("")
        self.zone_left_label.setText("")
        self.zone_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_left_label.setObjectName("zone_left_label")
        self.horizontalLayout_10.addWidget(self.zone_left_label)
        self.bay7_left_label = QtWidgets.QLabel(self.car7l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay7_left_label.setFont(font)
        self.bay7_left_label.setStyleSheet("")
        self.bay7_left_label.setText("")
        self.bay7_left_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay7_left_label.setObjectName("bay7_left_label")
        self.horizontalLayout_10.addWidget(self.bay7_left_label)
        self.verticalLayout_3.addWidget(self.car7l_frame)
        self.car8l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car8l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car8l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car8l_frame.setObjectName("car8l_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.car8l_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.num_plate8_label = QtWidgets.QLabel(self.car8l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate8_label.setFont(font)
        self.num_plate8_label.setStyleSheet("")
        self.num_plate8_label.setText("")
        self.num_plate8_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate8_label.setObjectName("num_plate8_label")
        self.horizontalLayout_11.addWidget(self.num_plate8_label)
        self.zone8_label = QtWidgets.QLabel(self.car8l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone8_label.setFont(font)
        self.zone8_label.setStyleSheet("")
        self.zone8_label.setText("")
        self.zone8_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone8_label.setObjectName("zone8_label")
        self.horizontalLayout_11.addWidget(self.zone8_label)
        self.bay8_label = QtWidgets.QLabel(self.car8l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay8_label.setFont(font)
        self.bay8_label.setStyleSheet("")
        self.bay8_label.setText("")
        self.bay8_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay8_label.setObjectName("bay8_label")
        self.horizontalLayout_11.addWidget(self.bay8_label)
        self.verticalLayout_3.addWidget(self.car8l_frame)
        self.car9l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car9l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car9l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car9l_frame.setObjectName("car9l_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.car9l_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.num_plate9_label = QtWidgets.QLabel(self.car9l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate9_label.setFont(font)
        self.num_plate9_label.setStyleSheet("")
        self.num_plate9_label.setText("")
        self.num_plate9_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate9_label.setObjectName("num_plate9_label")
        self.horizontalLayout_12.addWidget(self.num_plate9_label)
        self.zone9_label = QtWidgets.QLabel(self.car9l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone9_label.setFont(font)
        self.zone9_label.setStyleSheet("")
        self.zone9_label.setText("")
        self.zone9_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone9_label.setObjectName("zone9_label")
        self.horizontalLayout_12.addWidget(self.zone9_label)
        self.bay9_label = QtWidgets.QLabel(self.car9l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay9_label.setFont(font)
        self.bay9_label.setStyleSheet("")
        self.bay9_label.setText("")
        self.bay9_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay9_label.setObjectName("bay9_label")
        self.horizontalLayout_12.addWidget(self.bay9_label)
        self.verticalLayout_3.addWidget(self.car9l_frame)
        self.car10l_frame = QtWidgets.QFrame(self.left_body_frame)
        self.car10l_frame.setStyleSheet("")
        self.car10l_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car10l_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car10l_frame.setObjectName("car10l_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.car10l_frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.num_plate10_label = QtWidgets.QLabel(self.car10l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate10_label.setFont(font)
        self.num_plate10_label.setStyleSheet("")
        self.num_plate10_label.setText("")
        self.num_plate10_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate10_label.setObjectName("num_plate10_label")
        self.horizontalLayout_13.addWidget(self.num_plate10_label)
        self.zone10_label = QtWidgets.QLabel(self.car10l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone10_label.setFont(font)
        self.zone10_label.setStyleSheet("")
        self.zone10_label.setText("")
        self.zone10_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone10_label.setObjectName("zone10_label")
        self.horizontalLayout_13.addWidget(self.zone10_label)
        self.bay10_label = QtWidgets.QLabel(self.car10l_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay10_label.setFont(font)
        self.bay10_label.setStyleSheet("")
        self.bay10_label.setText("")
        self.bay10_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay10_label.setObjectName("bay10_label")
        self.horizontalLayout_13.addWidget(self.bay10_label)
        self.verticalLayout_3.addWidget(self.car10l_frame)
        self.verticalLayout.addWidget(self.left_body_frame)
        self.horizontalLayout_2.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_frame.setLineWidth(0)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right_head_frame = QtWidgets.QFrame(self.right_frame)
        self.right_head_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.right_head_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right_head_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_head_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_head_frame.setLineWidth(0)
        self.right_head_frame.setObjectName("right_head_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_head_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lp_header_right = QtWidgets.QLabel(self.right_head_frame)
        self.lp_header_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lp_header_right.setFont(font)
        self.lp_header_right.setAlignment(QtCore.Qt.AlignCenter)
        self.lp_header_right.setObjectName("lp_header_right")
        self.horizontalLayout_3.addWidget(self.lp_header_right)
        self.zone_header_right = QtWidgets.QLabel(self.right_head_frame)
        self.zone_header_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone_header_right.setFont(font)
        self.zone_header_right.setAlignment(QtCore.Qt.AlignCenter)
        self.zone_header_right.setObjectName("zone_header_right")
        self.horizontalLayout_3.addWidget(self.zone_header_right)
        self.lot_header_right = QtWidgets.QLabel(self.right_head_frame)
        self.lot_header_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lot_header_right.setFont(font)
        self.lot_header_right.setAlignment(QtCore.Qt.AlignCenter)
        self.lot_header_right.setObjectName("lot_header_right")
        self.horizontalLayout_3.addWidget(self.lot_header_right)
        self.verticalLayout_2.addWidget(self.right_head_frame)
        self.right_body_frame = QtWidgets.QFrame(self.right_frame)
        self.right_body_frame.setStyleSheet("color: rgb(255, 217, 61);")
        self.right_body_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_body_frame.setLineWidth(0)
        self.right_body_frame.setObjectName("right_body_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_body_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.car1r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car1r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car1r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car1r_frame.setLineWidth(0)
        self.car1r_frame.setObjectName("car1r_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.car1r_frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.num_plate1_right_label = QtWidgets.QLabel(self.car1r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate1_right_label.setFont(font)
        self.num_plate1_right_label.setStyleSheet("")
        self.num_plate1_right_label.setLineWidth(0)
        self.num_plate1_right_label.setText("")
        self.num_plate1_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate1_right_label.setObjectName("num_plate1_right_label")
        self.horizontalLayout_14.addWidget(self.num_plate1_right_label)
        self.zone1_right_label = QtWidgets.QLabel(self.car1r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone1_right_label.setFont(font)
        self.zone1_right_label.setStyleSheet("")
        self.zone1_right_label.setLineWidth(0)
        self.zone1_right_label.setText("")
        self.zone1_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone1_right_label.setObjectName("zone1_right_label")
        self.horizontalLayout_14.addWidget(self.zone1_right_label)
        self.bay1_right_label = QtWidgets.QLabel(self.car1r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay1_right_label.setFont(font)
        self.bay1_right_label.setStyleSheet("")
        self.bay1_right_label.setLineWidth(0)
        self.bay1_right_label.setText("")
        self.bay1_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay1_right_label.setObjectName("bay1_right_label")
        self.horizontalLayout_14.addWidget(self.bay1_right_label)
        self.verticalLayout_4.addWidget(self.car1r_frame)
        self.car2r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car2r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car2r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car2r_frame.setLineWidth(0)
        self.car2r_frame.setObjectName("car2r_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.car2r_frame)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.num_plate2_right_label = QtWidgets.QLabel(self.car2r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate2_right_label.setFont(font)
        self.num_plate2_right_label.setStyleSheet("")
        self.num_plate2_right_label.setText("")
        self.num_plate2_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate2_right_label.setObjectName("num_plate2_right_label")
        self.horizontalLayout_15.addWidget(self.num_plate2_right_label)
        self.zone2_right_label = QtWidgets.QLabel(self.car2r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone2_right_label.setFont(font)
        self.zone2_right_label.setStyleSheet("")
        self.zone2_right_label.setText("")
        self.zone2_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone2_right_label.setObjectName("zone2_right_label")
        self.horizontalLayout_15.addWidget(self.zone2_right_label)
        self.bay2_right_label = QtWidgets.QLabel(self.car2r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay2_right_label.setFont(font)
        self.bay2_right_label.setStyleSheet("")
        self.bay2_right_label.setText("")
        self.bay2_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay2_right_label.setObjectName("bay2_right_label")
        self.horizontalLayout_15.addWidget(self.bay2_right_label)
        self.verticalLayout_4.addWidget(self.car2r_frame)
        self.car3r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car3r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car3r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car3r_frame.setLineWidth(0)
        self.car3r_frame.setObjectName("car3r_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.car3r_frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.num_plate3_right_label = QtWidgets.QLabel(self.car3r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate3_right_label.setFont(font)
        self.num_plate3_right_label.setStyleSheet("")
        self.num_plate3_right_label.setText("")
        self.num_plate3_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate3_right_label.setObjectName("num_plate3_right_label")
        self.horizontalLayout_16.addWidget(self.num_plate3_right_label)
        self.zone3_right_label = QtWidgets.QLabel(self.car3r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone3_right_label.setFont(font)
        self.zone3_right_label.setStyleSheet("")
        self.zone3_right_label.setText("")
        self.zone3_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone3_right_label.setObjectName("zone3_right_label")
        self.horizontalLayout_16.addWidget(self.zone3_right_label)
        self.bay3_right_label = QtWidgets.QLabel(self.car3r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay3_right_label.setFont(font)
        self.bay3_right_label.setStyleSheet("")
        self.bay3_right_label.setText("")
        self.bay3_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay3_right_label.setObjectName("bay3_right_label")
        self.horizontalLayout_16.addWidget(self.bay3_right_label)
        self.verticalLayout_4.addWidget(self.car3r_frame)
        self.car4r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car4r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car4r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car4r_frame.setLineWidth(0)
        self.car4r_frame.setObjectName("car4r_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.car4r_frame)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.num_plate4_right_label = QtWidgets.QLabel(self.car4r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate4_right_label.setFont(font)
        self.num_plate4_right_label.setStyleSheet("")
        self.num_plate4_right_label.setText("")
        self.num_plate4_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate4_right_label.setObjectName("num_plate4_right_label")
        self.horizontalLayout_17.addWidget(self.num_plate4_right_label)
        self.zone4_right_label = QtWidgets.QLabel(self.car4r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone4_right_label.setFont(font)
        self.zone4_right_label.setStyleSheet("")
        self.zone4_right_label.setText("")
        self.zone4_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone4_right_label.setObjectName("zone4_right_label")
        self.horizontalLayout_17.addWidget(self.zone4_right_label)
        self.bay4_right_label = QtWidgets.QLabel(self.car4r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay4_right_label.setFont(font)
        self.bay4_right_label.setStyleSheet("")
        self.bay4_right_label.setText("")
        self.bay4_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay4_right_label.setObjectName("bay4_right_label")
        self.horizontalLayout_17.addWidget(self.bay4_right_label)
        self.verticalLayout_4.addWidget(self.car4r_frame)
        self.car5r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car5r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car5r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car5r_frame.setLineWidth(0)
        self.car5r_frame.setObjectName("car5r_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.car5r_frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.num_plate5_right_label = QtWidgets.QLabel(self.car5r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate5_right_label.setFont(font)
        self.num_plate5_right_label.setStyleSheet("")
        self.num_plate5_right_label.setLineWidth(0)
        self.num_plate5_right_label.setText("")
        self.num_plate5_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate5_right_label.setObjectName("num_plate5_right_label")
        self.horizontalLayout_18.addWidget(self.num_plate5_right_label)
        self.zone5_right_label = QtWidgets.QLabel(self.car5r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone5_right_label.setFont(font)
        self.zone5_right_label.setStyleSheet("")
        self.zone5_right_label.setText("")
        self.zone5_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone5_right_label.setObjectName("zone5_right_label")
        self.horizontalLayout_18.addWidget(self.zone5_right_label)
        self.bay5_right_label = QtWidgets.QLabel(self.car5r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay5_right_label.setFont(font)
        self.bay5_right_label.setStyleSheet("")
        self.bay5_right_label.setText("")
        self.bay5_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay5_right_label.setObjectName("bay5_right_label")
        self.horizontalLayout_18.addWidget(self.bay5_right_label)
        self.verticalLayout_4.addWidget(self.car5r_frame)
        self.car6r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car6r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car6r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car6r_frame.setLineWidth(0)
        self.car6r_frame.setObjectName("car6r_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.car6r_frame)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.num_plate6_right_label = QtWidgets.QLabel(self.car6r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate6_right_label.setFont(font)
        self.num_plate6_right_label.setStyleSheet("")
        self.num_plate6_right_label.setText("")
        self.num_plate6_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate6_right_label.setObjectName("num_plate6_right_label")
        self.horizontalLayout_19.addWidget(self.num_plate6_right_label)
        self.zone6_right_label = QtWidgets.QLabel(self.car6r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone6_right_label.setFont(font)
        self.zone6_right_label.setStyleSheet("")
        self.zone6_right_label.setText("")
        self.zone6_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone6_right_label.setObjectName("zone6_right_label")
        self.horizontalLayout_19.addWidget(self.zone6_right_label)
        self.bay6_right_label = QtWidgets.QLabel(self.car6r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay6_right_label.setFont(font)
        self.bay6_right_label.setStyleSheet("")
        self.bay6_right_label.setText("")
        self.bay6_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay6_right_label.setObjectName("bay6_right_label")
        self.horizontalLayout_19.addWidget(self.bay6_right_label)
        self.verticalLayout_4.addWidget(self.car6r_frame)
        self.car7r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car7r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car7r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car7r_frame.setLineWidth(0)
        self.car7r_frame.setObjectName("car7r_frame")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.car7r_frame)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.num_plate7_right_label = QtWidgets.QLabel(self.car7r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate7_right_label.setFont(font)
        self.num_plate7_right_label.setStyleSheet("")
        self.num_plate7_right_label.setText("")
        self.num_plate7_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate7_right_label.setObjectName("num_plate7_right_label")
        self.horizontalLayout_20.addWidget(self.num_plate7_right_label)
        self.zone7_right_label = QtWidgets.QLabel(self.car7r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone7_right_label.setFont(font)
        self.zone7_right_label.setStyleSheet("")
        self.zone7_right_label.setText("")
        self.zone7_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone7_right_label.setObjectName("zone7_right_label")
        self.horizontalLayout_20.addWidget(self.zone7_right_label)
        self.bay7_right_label = QtWidgets.QLabel(self.car7r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay7_right_label.setFont(font)
        self.bay7_right_label.setStyleSheet("")
        self.bay7_right_label.setText("")
        self.bay7_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay7_right_label.setObjectName("bay7_right_label")
        self.horizontalLayout_20.addWidget(self.bay7_right_label)
        self.verticalLayout_4.addWidget(self.car7r_frame)
        self.car8r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car8r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car8r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car8r_frame.setLineWidth(0)
        self.car8r_frame.setObjectName("car8r_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.car8r_frame)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.num_plate8_right_label = QtWidgets.QLabel(self.car8r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate8_right_label.setFont(font)
        self.num_plate8_right_label.setStyleSheet("")
        self.num_plate8_right_label.setText("")
        self.num_plate8_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate8_right_label.setObjectName("num_plate8_right_label")
        self.horizontalLayout_21.addWidget(self.num_plate8_right_label)
        self.zone8_right_label = QtWidgets.QLabel(self.car8r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone8_right_label.setFont(font)
        self.zone8_right_label.setStyleSheet("")
        self.zone8_right_label.setText("")
        self.zone8_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone8_right_label.setObjectName("zone8_right_label")
        self.horizontalLayout_21.addWidget(self.zone8_right_label)
        self.bay8_right_label = QtWidgets.QLabel(self.car8r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay8_right_label.setFont(font)
        self.bay8_right_label.setStyleSheet("")
        self.bay8_right_label.setText("")
        self.bay8_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay8_right_label.setObjectName("bay8_right_label")
        self.horizontalLayout_21.addWidget(self.bay8_right_label)
        self.verticalLayout_4.addWidget(self.car8r_frame)
        self.car9r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car9r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car9r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car9r_frame.setLineWidth(0)
        self.car9r_frame.setObjectName("car9r_frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.car9r_frame)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.num_plate9_right_label = QtWidgets.QLabel(self.car9r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate9_right_label.setFont(font)
        self.num_plate9_right_label.setStyleSheet("")
        self.num_plate9_right_label.setText("")
        self.num_plate9_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate9_right_label.setObjectName("num_plate9_right_label")
        self.horizontalLayout_22.addWidget(self.num_plate9_right_label)
        self.zone5_right_label_5 = QtWidgets.QLabel(self.car9r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone5_right_label_5.setFont(font)
        self.zone5_right_label_5.setStyleSheet("")
        self.zone5_right_label_5.setText("")
        self.zone5_right_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.zone5_right_label_5.setObjectName("zone5_right_label_5")
        self.horizontalLayout_22.addWidget(self.zone5_right_label_5)
        self.bay9_right_label = QtWidgets.QLabel(self.car9r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay9_right_label.setFont(font)
        self.bay9_right_label.setStyleSheet("")
        self.bay9_right_label.setText("")
        self.bay9_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay9_right_label.setObjectName("bay9_right_label")
        self.horizontalLayout_22.addWidget(self.bay9_right_label)
        self.verticalLayout_4.addWidget(self.car9r_frame)
        self.car10r_frame = QtWidgets.QFrame(self.right_body_frame)
        self.car10r_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.car10r_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car10r_frame.setLineWidth(0)
        self.car10r_frame.setObjectName("car10r_frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.car10r_frame)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.num_plate10_right_label = QtWidgets.QLabel(self.car10r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.num_plate10_right_label.setFont(font)
        self.num_plate10_right_label.setStyleSheet("")
        self.num_plate10_right_label.setLineWidth(0)
        self.num_plate10_right_label.setText("")
        self.num_plate10_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.num_plate10_right_label.setObjectName("num_plate10_right_label")
        self.horizontalLayout_23.addWidget(self.num_plate10_right_label)
        self.zone10_right_label = QtWidgets.QLabel(self.car10r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.zone10_right_label.setFont(font)
        self.zone10_right_label.setStyleSheet("")
        self.zone10_right_label.setText("")
        self.zone10_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.zone10_right_label.setObjectName("zone10_right_label")
        self.horizontalLayout_23.addWidget(self.zone10_right_label)
        self.bay10_right_label = QtWidgets.QLabel(self.car10r_frame)
        font = QtGui.QFont()
        font.setFamily("Mitr SemiBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.bay10_right_label.setFont(font)
        self.bay10_right_label.setStyleSheet("")
        self.bay10_right_label.setText("")
        self.bay10_right_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bay10_right_label.setObjectName("bay10_right_label")
        self.horizontalLayout_23.addWidget(self.bay10_right_label)
        self.verticalLayout_4.addWidget(self.car10r_frame)
        self.verticalLayout_2.addWidget(self.right_body_frame)
        self.horizontalLayout_2.addWidget(self.right_frame)
        BigMonitor.setCentralWidget(self.centralwidget)

        self.retranslateUi(BigMonitor)
        QtCore.QMetaObject.connectSlotsByName(BigMonitor)

    def retranslateUi(self, BigMonitor):
        _translate = QtCore.QCoreApplication.translate
        BigMonitor.setWindowTitle(_translate("BigMonitor", "Big Screen"))
        self.label.setText(_translate("BigMonitor", "ทะเบียน"))
        self.label_2.setText(_translate("BigMonitor", "โซน"))
        self.label_3.setText(_translate("BigMonitor", "ช่องจอด"))
        self.lp_header_right.setText(_translate("BigMonitor", "ทะเบียน"))
        self.zone_header_right.setText(_translate("BigMonitor", "โซน"))
        self.lot_header_right.setText(_translate("BigMonitor", "ช่องจอด"))
